### ISSUE TITLE
Endpoint para validar se código do usuário já foi utilizado

### ISSUE THREAD

**Issue by salazenas** [codenation-dev/squad-3-ad-java-e-vue-presencial-ca-front#14]
Durante o cadastro do usuário, é preciso validar se o código do usuário já foi utilizado após ele inserir o valor no campo "Código do Usuário".

Assim o usuário evita de enviar o formulário completo com um código de usuário indisponível.

Uma imagino uma requisição do tipo POST passando o valor do código 

/users/isAvaliable/{id}

mas não sei as boas praticas para API.

**Comment by devmanfredi** [comment]
vou verificar
